import { InputHTMLAttributes, PropsWithChildren } from 'react';

export const getInputAttributes = <T>(props: PropsWithChildren<InputHTMLAttributes<T>>): InputHTMLAttributes<T> => ({
  accept: props.accept,
  alt: props.alt,
  autoComplete: props.autoComplete,
  capture: props.capture,
  checked: props.checked,
  crossOrigin: props.crossOrigin,
  disabled: props.disabled,
  enterKeyHint: props.enterKeyHint,
  form: props.form,
  formAction: props.formAction,
  formEncType: props.formEncType,
  formMethod: props.formMethod,
  formNoValidate: props.formNoValidate,
  formTarget: props.formTarget,
  height: props.height,
  list: props.list,
  max: props.max,
  maxLength: props.maxLength,
  min: props.min,
  minLength: props.minLength,
  multiple: props.multiple,
  name: props.name,
  pattern: props.pattern,
  placeholder: props.placeholder,
  readOnly: props.readOnly,
  required: props.required,
  size: props.size,
  src: props.src,
  step: props.step,
  type: props.type,
  value: props.value,
  width: props.width
});
